[[stack]]
name = "oeils-baserow"
tags = ["oeils"]
[stack.config]
server = "cartons"
links = [
  "https://oeils-baserow.constructions-incongrues.net"
]
poll_for_updates = true
linked_repo = "oeils-main"
run_directory = "stacks/baserow"
environment = """
GENERIC_TIMEZONE=Europe/Paris
DOMAIN_NAME=constructions-incongrues.net
SUBDOMAIN=oeils-baserow
"""

##

[[stack]]
name = "oeils-n8n"
tags = ["oeils"]
[stack.config]
server = "cartons"
links = [
  "https://oeils-n8n.constructions-incongrues.net"
]
poll_for_updates = true
linked_repo = "oeils-main"
run_directory = "stacks/n8n"
environment = """
GENERIC_TIMEZONE=Europe/Paris
DOMAIN_NAME=constructions-incongrues.net
SUBDOMAIN=oeils-n8n
"""

##

[[resource_sync]]
name = "oeils"
tags = ["oeils"]
[resource_sync.config]
linked_repo = "oeils-main"
resource_path = [
  "infrastructure/resources.toml",
  "stacks/n8n"
]
managed = true
match_tags = ["oeils"]